# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/petr/Projects/fpga/redpitaya/wrk/Smart_JTAG_cable/rtl/src/const/top_pins.xdc

# Block Designs: bd/processor/processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor || ORIG_REF_NAME==processor} -quiet] -quiet

# IP: bd/processor/ip/processor_processing_system7_0_0/processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_processing_system7_0_0 || ORIG_REF_NAME==processor_processing_system7_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_jtag_cable_comm_0_0/processor_jtag_cable_comm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_jtag_cable_comm_0_0 || ORIG_REF_NAME==processor_jtag_cable_comm_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_ps7_0_axi_periph_0/processor_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_ps7_0_axi_periph_0 || ORIG_REF_NAME==processor_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/processor/ip/processor_clk_wiz_0/processor_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0 || ORIG_REF_NAME==processor_clk_wiz_0} -quiet] -quiet

# IP: bd/processor/ip/processor_rst_clk_wiz_100M_0/processor_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_rst_clk_wiz_100M_0 || ORIG_REF_NAME==processor_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/processor/ip/processor_auto_pc_0/processor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_auto_pc_0 || ORIG_REF_NAME==processor_auto_pc_0} -quiet] -quiet

# XDC: bd/processor/processor_ooc.xdc
